### ISSUE TITLE
Only works on PDF files

### ISSUE THREAD

**Issue by lbdroid** [R0Wi/workflow_ocr#107]
## Steps to reproduce
1. Install
2. Try to OCR on an image

### Expected behaviour
Convert the image to PDF (add or change file extension), then OCR
Bonus: If ocrmypdf doesn't exist, still convert the file to PDF.
Alternatively, and maybe better even, if the mimetype is NOT application/pdf, ONLY perform the file type conversion, allowing the user to set up separate flows for the conversion and ocr parts of the job.

The "convert" command, which is part of imagemagick, can perform the conversion on stdin/out using "convert - PDF:-"

Points for implementation;
1) lib/BackgroundJobs/ProcessFileJob.php, processFile:
if $node->getMimeType() != application/pdf, alter $filePath with extension ".pdf".

2) lib/OcrProcessors/OcrProcessorFactory.php:
Add image type mappings to new OcrProcessor, i.e. 'image/jpeg' => ImageOcrProcessor::class

3) create new lib/OcrProcessors/ImageOcrProcessor.php much like PdfOcrProcessor.php, but with convert command as above.

### Actual behaviour
No actual conversion, error log "OCR processor not found for mimetype image/jpeg

**Comment by R0Wi** [comment]
Included in `v1.24.1` and `v1.23.3` 😎
