### ISSUE TITLE
I can't choose the language I need in the settings. There are only a few languages to choose from the box

### ISSUE THREAD

**Issue by aquliu** [R0Wi/workflow_ocr#119]
I installed the extra teerract language pack I needed, but the language I needed was not listed in nextcloud.

**Comment by R0Wi** [comment]
Thanks for your feedback. Unfortunately there is currently no link between the language options shown in the UI and the languages you have installed for tesseract on your system. At the moment this is just a hardcoded list with the most common languages. 

As a first step i'd add your desired language to the mentioned static list. One step further could be to read the available languages from the backend system and show them in the UI.

Which language do you miss?

**Comment by aquliu** [comment]
I really appreciate your doing so. I hope to add Simplified Chinese, which is written as chi_sim&nbsp;on the command line. Because I need to deal with a lot of Chinese papers. That will do me a big favor.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Robin ***@***.***&gt;; 
发送时间: 2022年5月18日(星期三) 晚上8:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [R0Wi/workflow_ocr] I can&#39;t choose the language I need in the settings. There are only a few languages to choose from the box (Issue #119)





 
Thanks for your feedback. Unfortunately there is currently no link between the language options shown in the UI and the languages you have installed for tesseract on your system. At the moment this is just a hardcoded list with the most common languages.
 
As a first step i'd add your desired language to the mentioned static list. One step further could be to read the available languages from the backend system and show them in the UI.
 
Which language do you miss?

**Comment by R0Wi** [comment]
Included in `v1.24.1` and `v1.23.3` 😎
