### ISSUE TITLE
Make OCR skip options configurable

### ISSUE THREAD

**Issue by R0Wi** [R0Wi/workflow_ocr#129]
As a result of #113 we should make the options `--skip-text`, `--redo-ocr` and `--force-ocr` configurable through our per workflow settings UI. Also we should have an option so choose none of these parameters (see #130)

- [x] Add a flag to the model
- [x] Add radiobuttons to per workflow settings UI
- [x] Make `redo-ocr` mutially exclusive with `remove-background` (latter is not possible in `redo-ocr`-mode)

**Comment by jkumeboshi** [comment]
With skip-text as default, documents created with camscanner or other similar SW adding some text to the scanned images fails ("scanned with CamScanner" is enough to stop the  skip-text option).

I think that this setting could be added to the workflow settings.
So I would create 2 kind of tag forkflow: 1 with redo-ocr or force-ocr and another with skip-text
So I could use the force-ocr workflow with documents coming from camscanner

**Comment by R0Wi** [comment]
@jkumeboshi I implemented the configuration possibility now. Could you image beta testing the new feature and give me some feedback?
