### ISSUE TITLE
Error handling jpgs

### ISSUE THREAD

**Issue by stepqom** [R0Wi/workflow_ocr#131]
Hi,

there is a little error  in handling jpgs (I think pngs too).
The generated command line is
ocrmypdf -q --skip-text -l deu+eng--image-dpi 300  - - | cat
should be
ocrmypdf -q --skip-text -l deu+eng --image-dpi 300  - - | cat
Space between deu+eng and --image-dpi is missing.
In ImageOcrProcessor.php I added spaces around the returned value and it worked. 
Please excuse that I don't deliver a pull request. I'm not a expert in php, so I guess there will be a better solution than my. 

By the way, good software!

**Comment by R0Wi** [comment]
Thank's for reporting this. Will be fixed soon :-)
