### ISSUE TITLE
Dispatch OCP Event with OcrProcessorResult

### ISSUE THREAD

**Issue by g-schmitz** [R0Wi/workflow_ocr#144]
Hey,

it would be nice to have workflow_ocr dispatch an [OCP Event](https://docs.nextcloud.com/server/latest/developer_manual/basics/events.html#ocp-event-dispatcher). 

I'm currently developing my own app for nextcloud and it would be very helpful plus more efficient to be able to hook in and directly get the processed OCR text for each file instead of parsing the finished PDF afterwards.

If desired can help with implementation and submit a PR.

**Comment by R0Wi** [comment]
Thank's for your feedback. In general this should be no big deal. To provide the OCR text content i think we have to introduce the `--sidecar` option of ocrMyPdf (see also https://github.com/R0Wi/workflow_ocr/issues/130#issuecomment-1167465369).

If you'd like to help please feel free to make a PR 👍
