### ISSUE TITLE
user flow

### ISSUE THREAD

**Issue by jospoortvliet** [R0Wi/workflow_ocr#16]
Hi,

First - great app, really nice work! Second, I was wondering if you could make it possible for users, instead of just admins, to create flows with this ;-)

Also, did you think about giving a short talk about your app and dev experience on the Nextcloud conference? We would love to have you ;-)

**Comment by R0Wi** [comment]
Hey @jospoortvliet , 

thanks for your feedback, really glad to hear that you like the app :-)

So to come to your questions:

1. The app setup is indeed a bit complicated and error prone at the moment. Currently @bahnwaerter and i are working on an container based backend which would make things much easier to configure and deploy. But i thinkt if all the setup stuff is done and the system is working correctly it should be as easy for any user to create a new flow with this app as it is with any other flow based app or am i missing something? Maybe you could give some advice what could be improved from a users point of view ? :-)
2. I'd be very happy to give a short recap on you Nexcloud dev conference. So maybe we could clear things reagarding this via PM?

**Comment by jospoortvliet** [comment]
For the conference part, you can just submit something on https://eventyay.com/e/0917096d/cfs and a colleague will get in contact!

With regards to how hard it is to set this up - a properly configured Nextcloud server would not have many issues, correct? Imagick is an optional/recommended requirement of Nextcloud and if it's there it should work. The main issue seems tesseract - something the admin would have to install.

I would say there are a few options.
1. Create an installation check (in the admin settings overview) that points ppl to the docs here if there is a problem detected. Then ppl will find and fix it ;-) You could also do a admin notification.
2. Bundle one or more of the dependencies with the app, or a separate app, like we are doing with Mail, Talk and Collabora - like https://apps.nextcloud.com/apps/talk_matterbridge (this IS a bit nasty! Esp with security-critical things... but much easier than docker as it 'just works' on most systems)

Of course, a combination of the two is also possible - tell people there are two solutions to the problem identified under point 1: install the 'tesseract-backend' app or install php-imagemagick and tesseract. Or even - run a docker image ;-)

**Comment by R0Wi** [comment]
Thanks for your feedback 👍  I'm going to evaluatea good solution these days and will then create new issues. Will leave this one open in the meantime ...

**Comment by tacruc** [comment]
I read the Issue, but I didn't get the point why it is not listed under settings/user/workflow?
I see that it has to be configured once for the instance, but then it would be nice to be able to set a workflow individual for the user.

**Comment by R0Wi** [comment]
@tacruc maybe i did somesthing wrong when registering this app as workflow app. Could you give me an example for a workflow app where workflows can be configured per user? I'd then compare with this...

**Comment by tacruc** [comment]
https://github.com/nextcloud/workflow_pdf_converter

**Comment by R0Wi** [comment]
I think this is responsible:
https://github.com/R0Wi/workflow_ocr/blob/2d74b57f669286388480a561b681930cf72cd731/lib/Operation.php#L78

Will fix that. @bahnwaerter FYI

**Comment by tacruc** [comment]
Nice Thanks :+1:
