### ISSUE TITLE
Can not ocr pdf files as input

### ISSUE THREAD

**Issue by FadeFx** [R0Wi/workflow_ocr#167]
Hi, i was playing a while ad could not find out what is my issue, workflow_ocr did not seem to work. My only trigger was a collaborative tag (ocrme). 
However, when I tried to use a file created and mimetype pdf i found out that pdf was not allowed, so i created a jpg from one pdf and added my tag. That moment my server began to ocr the file and saved it as a pdf. 
My question is, why is it not possible to handle PFD files? Am I holding it wrong? ;-)

**Comment by FadeFx** [comment]
Yes, i can set it up, but if I tag a pdf file it will not be processed, however jpg files will be. 
If I try to add a filter for specific mime type pdf i can not save the workflow the save button turns orange saying the configuration is invalid and an additional error message that the regular expression is invalid
![Screenshot_20221204-202117_1](https://user-images.githubusercontent.com/41125748/205510940-ba5cc989-444b-4472-9ca0-eebdd6a879cd.png)
Sorry screenshot is German and from phone...

**Comment by R0Wi** [comment]
Could be you're hiting https://github.com/nextcloud/server/issues/23666#issuecomment-785647870. Please try "is" instead of "matches" before the mimetype PDF setting

**Comment by FadeFx** [comment]
That works and now pdfs get ocr'd thank you... Strange that it did not do this without any mime type filter ...

**Comment by R0Wi** [comment]
Glad to help. Hope this will be fixed in NC workflowengine soon 👍
