### ISSUE TITLE
Skip files which already have OCR content

### ISSUE THREAD

**Issue by ufgum** [R0Wi/workflow_ocr#173]
There are option for `--skip-text`, `--redo-ocr` and `--force-ocr,` but no option to pass all of these commands. 
Without these commands, `ocrmypdf` just skip the file.

I have e few thousand files, need to copy to the cloud and need OCR on the files without text, so it would help a lot to skip already OCR'ed files.

**Comment by ufgum** [comment]
I think an option wihtout flags. As they write:

`If a page in a PDF seems to have text, by default OCRmyPDF will exit without modifying the PDF. This is to ensure that PDFs that were previously OCRed or were “born digital” rather than scanned are not processed.`

So, if I call ocrmypdf wihtout flags on an OCR'ed file I get this on command line:

```
Scanning contents: 100%|███████████████████████████████████████████| 1/1 [00:00<00:00, 55.44page/s]
OCR:   0%|                                                                                                                            | 0.0/1.0 [00:00<?, ?page/s]
PriorOcrFoundError: page already has text! - aborting (use --force-ocr to force OCR;  see also help for the arguments --skip-text and --redo-ocr
```
You see, it will just abort, without changing anything on file. This makes sense, to not OCR same file many times.

**Comment by R0Wi** [comment]
Ok agree. So the feature request here would be to have an additional [per workflow](https://github.com/R0Wi/workflow_ocr#per-workflow-settings) OCR mode `none`, which under the hood just calls `ocrmypdf` without any of the mentioned flags?

Btw.: in the meantime as a workaround you could use `--skip-text`. According to the docs:

> If --skip-text is issued, then no image processing or OCR will be performed on pages that already have text. The page will be copied to the output. This may be useful for documents that contain both “born digital” and scanned content, or to use OCRmyPDF to normalize and convert to PDF/A regardless of their contents.

`ocrmypdf` will still walk through the whole PDF and create a new document, so the process will be slower. But the result should be comparable to calling it without any flags, beside the fact, that non-ocr pages gets processed.

**Comment by ufgum** [comment]
I had some files that got bigger with the `--skip-text` flag. Input file-size was 46KB, output was 112KB. Running again these file, it grows from 112KB to 146KB.

So you can imagine what will happens, if a user scan thousand of files more than once. Could also happens accidentally by misconfigure the workflow. Or like in my case some are OCRed, some not.

**Comment by R0Wi** [comment]
I agree with you that adding an option for OCR mode `none` makes sense. But in general it shouldn't happen too often that files are processed via OCR multiple times (at least not when only using this app with the "file created" trigger). So yeah the feature definitely makes sense but I also think you're hitting an edge-case here 😺 

If anyone is interested, PR welcome btw 👍
