### ISSUE TITLE
There are only tags with the letter A ?! :000 (clickbait) <3

### ISSUE THREAD

**Issue by twerpyfie** [R0Wi/workflow_ocr#175]
Thanks for the great work :)

To get straight to the point:

If I add a new process and select the rule with the collaborative tag, then I can only select all tags that begin with A as the tag. Unfortunately, the rest (e.g. "Document") cannot be entered.

Have a nice day :)

**Comment by twerpyfie** [comment]
Hm i tested it again and now it works.. Idk sorry. Maby its my fault.

**Comment by R0Wi** [comment]
Think currently the result set is limited to 5 entries because of the dropdown component we're using. Could it be related to this?

**Comment by twerpyfie** [comment]
I dont know exactly if this could be, but i dont think so. When i enter "Document" in the Field, i cant select everything.
When i just put the letter D in it, it sorts everything out except the Tags with the letter "d" in, but only from the first 5 entrys.... Is that reproducible for you? It's a bit difficult to explain. 

Without text:
![1](https://user-images.githubusercontent.com/46491831/213824245-59ac69ec-972b-48d6-a793-980f188a608a.png)

With just the letter "d"
![2](https://user-images.githubusercontent.com/46491831/213824247-6943067d-3586-4374-a8db-5f8be007e66f.png)

Selfexplaining:
![3](https://user-images.githubusercontent.com/46491831/213824249-ce7148fa-b850-49b1-9465-b8fa6a734304.png)

The tag "Document" does exist:
![4](https://user-images.githubusercontent.com/46491831/213824250-a0003702-ea05-43ec-927e-7a00c4283e8d.png)

Thanks for the quick answer :)

**Comment by R0Wi** [comment]
Sound a bit strange indeed. Well I was talking about the "Add tag" and "Remove tag" boxes on the right hand side. Everything which belongs to the "conditions" section on the left is coming from the workflowengine itself which is part of the NC server project. If you're facing problems there, you should open an issue in nextcloud/server.

Cheers

**Comment by twerpyfie** [comment]
Yes, the box on the left works like a charm. Okay i will do that, thank you for your time 🥇

**Comment by R0Wi** [comment]
You're welcome and thank's for your effort, too 👍  Will close this for now, please feel free to reopen if needed.
