### ISSUE TITLE
Workflow triggered by collaborative tag is not saved properly

### ISSUE THREAD

**Issue by nwinkelstraeter** [R0Wi/workflow_ocr#179]
## Steps to reproduce
1. Create OCR Workflow that triggers on Tag
2. Select Tag to trigger on
3. Select other settings, save and reload
4. Tag field is now empty and Workflow does not Trigger on the selected Tag

### Expected behaviour
The Tag should be saved and the workflow should be executed on files that get tagged with it

### Actual behaviour
Tag field in settings is empty after saving and Workflow does not Trigger on the selected Tag

## Workflow OCR App

**Workflow OCR app version:**   1.25.2
## Server configuration

**Operating system**:  Docker Deployment

**Nextcloud Version:**  25.0.3

**Comment by R0Wi** [comment]
Thank's for reporting this. Could be a bug in the workflowengine itself which does not belong to this app. Could you please try if the same behaviour occures with a different workflow app?

**Comment by nwinkelstraeter** [comment]
I tried it with other workflow apps and the same issue occurs.
So i guess it is an issue with the workflow engine and there already is an issue in the nextcloud server repo https://github.com/nextcloud/server/issues/35645
I guess i wasn't thorough enough when searching for existing issues.

Anyways, thanks for your answer and sorry for unnecessarily opening this issue.

**Comment by R0Wi** [comment]
No worries at all, hope this issue will get fixed soon 🙏

**Comment by R0Wi** [comment]
@nwinkelstraeter I just tested this behaviour on my private cloud and for me it looks like this could be "only" a frontend issue. When I configure a new OCR workflow to trigger on a specific tag assignment, after saving and reloading the settings page the dropdown for the tag gets emptied. But: if I tag a PDF file with the tag I used in the settings, I can see that inside the `oc_jobs` SQL table a new record is created with class `OCA\WorkflowOcr\BackgroundJobs\ProcessFileJob`. That means, the file should be processed correctly in the next cron run.

> [...] and Workflow does not Trigger on the selected Tag

Could you please confirm this behaviour by

1. Configuring a tag assignment as OCR trigger in workflow settings
2. Assign this tag to a PDF document
4. Check the `oc_jobs` table or run `sudo -u www-data php cron.php` to verifiy that the tag assignment has queued the file for OCR processing

Think that would make it easier to find the bug. Thanks

**Comment by nwinkelstraeter** [comment]
@R0Wi 
Ok, I just did this and it works like you described. A job appears in `oc_jobs`
I must have had a mistake in my initial workflow and assumed the reason it doesn't work is because the tag is not shown properly.

**Comment by R0Wi** [comment]
Thanks for your effort, I think that could help a lot. Maybe I'll find some time this weekend to help the DEV team of the NC workflowengine fixing that bug 👍

**Comment by benmprojects** [comment]
This is also affecting the Block file access flows. The cron jobs appear to be working but cannot add any new jobs with new tags as they dont appear in the drop down menu.
