### ISSUE TITLE
small correction to installation guide

### ISSUE THREAD

**Issue by PiotrEsse** [R0Wi/workflow_ocr#19]
Hi, really great app - much needed, but need to work ;-D
I followed installation manual. 
I found in error log following errors: 
`ImagickException: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408`

It seems You need to restart not only web server but also FPM service, in my case 7.3 

`sudo systemctl restart php7.3-fpm.service`

Please add this info for others.

**Comment by R0Wi** [comment]
Thanks for your feedback. To be honest i'm a bit confused that a restart of your `fpm` service fixed this issue? The processing with `Imagick` is done in the background usually triggered by [`cron.php`](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html?highlight=background%20job#cron) if you configured NC to use `crontab` for backround job execution.

So do you use [`AJAX`](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html?highlight=background%20job#ajax) or [`Webcron`](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html?highlight=background%20job#webcron) for this?

**Comment by PiotrEsse** [comment]
maybe thats why lib is called imageMAGIC. Its magic how it works ;-D
 anyway Ive tried many options in policy.xml (read|write, disable whole policy section etc) - none worked. Until Ive resrarted also FPM ;-)

**Comment by R0Wi** [comment]
Just to know: could you share which setting you have activated at `Settings -> Basic settings -> Background jobs`?
![image](https://user-images.githubusercontent.com/19730957/94925299-44889b00-04bf-11eb-904b-873bef74a716.png)
