### ISSUE TITLE
PDF files are getting bloating up

### ISSUE THREAD

**Issue by thomasgg23** [R0Wi/workflow_ocr#22]
Thanks for the nice integration in workflow.

Tried some files to ocr but with the combination of scripts in the PdfOcrProcessor.php.
Some files are getting 5x bigger after the ocr process.

The best tool I found so far is OCRmyPDF (https://github.com/jbarlow83/OCRmyPDF) which do some "magick" to the pdf files and get really good results and the file size is quite the same (some 100kb plus).

Perhaps the OCRmyPDF could be integrated as another Processor (my coding skills are not good enough for that).

**Comment by R0Wi** [comment]
Thanks for reporting this. We're aware that the current version has issues regarding the compression of the output pdf files. 

The idea was that the app can handle "mixed" input pdf files where some pages contain text and some contain scanned images for example. OcrMyPdf does not take care of this and instead also transforms regular text pages to "images" inside of the output pdf.

We're currently working on a solution so stay tuned :-)

**Comment by thomasgg23** [comment]
Ok nice to hear. Thanks.

**Comment by col-panic** [comment]
Just experienced the same - a pdf with 4.5mb gets bloat up to 45mb !

**Comment by R0Wi** [comment]
> Just experienced the same - a pdf with 4.5mb gets bloat up to 45mb !

That sounds really bad :-/ @bahnwaerter and i are currently working on an independend backend for this app which tackles this problem (and it will simplify the setup and much more). But since this is a bigger task we could discuss if we can improve the app in the near future.

So for me the suggestion from @thomasgg23 to integrate `OCRmyPDF` sounds really good i think this tool is aware of various compression algorithms which won't blow up the original PDF files too much. But the disadvantage i see is that it can't handle "mixed" PDF files which contains text as well as images. 

So @thomasgg23 @col-panic do you primarily work with PDF files which only contains (scanned) images or are there also "mixed" ones you would like to process via OCR?

**Comment by thomasgg23** [comment]
@R0Wi I think this is possible also with mixed ones.

See option "--skip-text" https://ocrmypdf.readthedocs.io/en/latest/advanced.html#when-ocr-is-skipped

I tried a sample file with one "text image" (page 1) and "text" (page2) and it seems like the script skips page2 
> 2 skipping all processing on this page

Sample file before ocr [Non-text-searchable.pdf](https://github.com/R0Wi/workflow_ocr/files/5367017/Non-text-searchable.pdf) and after [Non-text-searchable_ocr.pdf](https://github.com/R0Wi/workflow_ocr/files/5367018/Non-text-searchable_ocr.pdf)

Full log here:
>  /usr/local/bin/ocrmypdf -v -l deu+eng --skip-text Non-text-searchable.pdf Non-text-searchable_ocr.pdf
ocrmypdf 11.1.1
Running: ['tesseract', '--list-langs']
Running: ['tesseract', '--version']
Found tesseract 4.1.1
Running: ['tesseract', '-l', 'deu+eng', '--print-parameters', 'pdf']
Running: ['gs', '--version']
Found gs 9.50
pikepdf mmap disabled
os.symlink(Non-text-searchable.pdf, /tmp/com.github.ocrmypdf.e6j_goap/origin)
os.symlink(/tmp/com.github.ocrmypdf.e6j_goap/origin, /tmp/com.github.ocrmypdf.e6j_goap/origin.pdf)
pikepdf mmap disabled
Scanning contents: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 168.55page/s]
Start processing 2 pages concurrently
pikepdf mmap disabled
pikepdf mmap disabled
    2 Page rotation: (content, auto) -> page = (0, 0) -> 0
    2 skipping all processing on this page
    1 Rasterize with png16m
    1 Running: ['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-sDEVICE=png16m', '-dFirstPage=1', '-dLastPage=1', '-r339.924461x339.924461', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/com.github.ocrmypdf.e6j_goap/origin.pdf']
    1 resolution (340, 340)
    1 Running: ['tesseract', '-l', 'deu+eng', '-c', 'textonly_pdf=1', PosixPath('/tmp/com.github.ocrmypdf.e6j_goap/000001_ocr.png'), '/tmp/com.github.ocrmypdf.e6j_goap/000001_ocr_tess', 'pdf', 'txt']
    1 Grafting
    1 Page rotation: (content, auto) -> page = (0, 0) -> 0
OCR: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.0/2.0 [00:03<00:00,  1.82s/page]
Postprocessing...
Running: ['gs', '-dQUIET', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dCompatibilityLevel=1.6', '-sDEVICE=pdfwrite', '-dAutoRotatePages=/None', '-sColorConversionStrategy=RGB', '-dAutoFilterColorImages=true', '-dAutoFilterGrayImages=true', '-dJPEGQ=95', '-dPDFA=2', '-dPDFACompatibilityPolicy=1', '-o', '-', '-sstdout=%stderr', '/tmp/com.github.ocrmypdf.e6j_goap/fix_docinfo.pdf', '/tmp/com.github.ocrmypdf.e6j_goap/pdfa.ps']
stderr = GPL Ghostscript 9.50: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set
Ghostscript had to remove PDF 'overprinting' from the input file to complete PDF/A conversion.
XrefExt(xref=27, ext='.png')
Optimizable images: JPEGs: 0 PNGs: 1
JPEGs: 0image [00:00, ?image/s]
Optimizable images: JBIG2 groups: (0,)
JBIG2: 0item [00:00, ?item/s]
Optimize ratio: 1.00 savings: 0.0%
os.symlink(/tmp/com.github.ocrmypdf.e6j_goap/optimize.opt.pdf, /tmp/com.github.ocrmypdf.e6j_goap/optimize.pdf)
/tmp/com.github.ocrmypdf.e6j_goap/optimize.pdf -> Non-text-searchable_ocr.pdf
Output file is a PDF/A-2B (as expected)

**Comment by thomasgg23** [comment]
Forgot to answer your question ;-)

98% I use the ocr on files that only contains scanned "images"
2% with mixed content

**Comment by R0Wi** [comment]
Thanks for your feedback. Will evaluate this and keep you up to date :-)

If we integrate `OcrMyPDF` could you imagine beta testing?

**Comment by thomasgg23** [comment]
Sure no problem, have a test server on hand and everyday enough scanned pdf files to test

**Comment by col-panic** [comment]
We are working mostly with PDFs generated by a scanner, so I guess they are all images. What would come in handy, is also to be able to configure the executable. We tried OCRmyPDF and used the flags `-l deu --deskew --sidecar`. For the current plugin I don't see a way, e.g. to configure tesseract parameters.

**Comment by thomasgg23** [comment]
@col-panic I only use "--skip-text" flag, I tried some other "improvment" flags before but one or two files get corrupted and so we decided to stay safe and don't do to much optimization.

**Comment by R0Wi** [comment]
Ok we decided to integrate `OCRmyPDF` (see https://github.com/R0Wi/workflow_ocr/issues/32 for progress). Could be that we start with hard-coded flags and create a configuration afterwards, lets see :-)

Closing this.
