### ISSUE TITLE
ArgumentCountError

### ISSUE THREAD

**Issue by dst21** [R0Wi/workflow_ocr#35]
Hello,

I get the error below in a Nextcloud instance with PHP7.4-FPM and Ngnix web server. The app works in another instance with Apache2 and PHP7.2. The rules are structured as follows in both instances: Condition: if the file is created and the MIME type is PDF document

`ArgumentCountError: Too few arguments to function thiagoalessio\TesseractOCR\TesseractOCR::__construct(), 0 passed in /daten/nextcloud/apps/workflow_ocr/lib/Wrapper/TesseractOcrWrapper.php on line 36 and at least 1 expected
/daten/nextcloud/apps/workflow_ocr/lib/Wrapper/TesseractOcrWrapper.php - line 36:

thiagoalessio\TesseractOCR\TesseractOCR->__construct()

<<closure>>

OCA\WorkflowOcr\Wrapper\TesseractOcrWrapper->__construct()

/daten/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 101:

ReflectionClass->newInstanceArgs()

/daten/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 109:

OC\AppFramework\Utility\SimpleContainer->buildClass()

/daten/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 126:

OC\AppFramework\Utility\SimpleContainer->resolve()

/daten/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 455:

OC\AppFramework\Utility\SimpleContainer->query()

/daten/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 427:

OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()

/daten/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 56:

OC\AppFramework\DependencyInjection\DIContainer->query()

/daten/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 177:

OC\AppFramework\Utility\SimpleContainer->get()

/daten/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 155:

OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")

/daten/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php - line 114:

OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")

/daten/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 122:

Pimple\Container->offsetGet()

/daten/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 449:

OC\AppFramework\Utility\SimpleContainer->query()

/daten/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 427:

OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()

/daten/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 87:

OC\AppFramework\DependencyInjection\DIContainer->query()

<<closure>>

OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")

/daten/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 101:

array_map()

/daten/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 109:

OC\AppFramework\Utility\SimpleContainer->buildClass()

/daten/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 126:

OC\AppFramework\Utility\SimpleContainer->resolve()

/daten/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 455:

OC\AppFramework\Utility\SimpleContainer->query()

/daten/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 427:

OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()

/daten/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 56:

OC\AppFramework\DependencyInjection\DIContainer->query()

/daten/nextcloud/apps/workflow_ocr/lib/OcrProcessors/OcrProcessorFactory.php - line 47:

OC\AppFramework\Utility\SimpleContainer->get()

/daten/nextcloud/apps/workflow_ocr/lib/Service/OcrService.php - line 41:

OCA\WorkflowOcr\OcrProcessors\OcrProcessorFactory->create()

/daten/nextcloud/apps/workflow_ocr/lib/BackgroundJobs/ProcessFileJob.php - line 192:

OCA\WorkflowOcr\Service\OcrService->ocrFile()

/daten/nextcloud/apps/workflow_ocr/lib/BackgroundJobs/ProcessFileJob.php - line 157:

OCA\WorkflowOcr\BackgroundJobs\ProcessFileJob->ocrFile()

/daten/nextcloud/apps/workflow_ocr/lib/BackgroundJobs/ProcessFileJob.php - line 96:

OCA\WorkflowOcr\BackgroundJobs\ProcessFileJob->processFile()

/daten/nextcloud/lib/private/BackgroundJob/Job.php - line 52:

OCA\WorkflowOcr\BackgroundJobs\ProcessFileJob->run()

/daten/nextcloud/lib/private/BackgroundJob/QueuedJob.php - line 46:

OC\BackgroundJob\Job->execute()

/daten/nextcloud/cron.php - line 127:

OC\BackgroundJob\QueuedJob->execute()`

**Comment by R0Wi** [comment]
Thanks for reporting this. Since we're currently working on a refactoring of the backend in https://github.com/R0Wi/workflow_ocr/issues/32 the mentioned component is likely to be removed in the future. Maybe you would like to test the new version by checking out the artifact at https://github.com/R0Wi/workflow_ocr/suites/1346287870/artifacts/21769925. Feedback would be very appreciated.

**Comment by dst21** [comment]
i have tested this Version and it seems to work.

**Comment by R0Wi** [comment]
Please make sure you only use the `File created` event and remove the `File edited` for now (see https://github.com/R0Wi/workflow_ocr/issues/32#issuecomment-724764647).

Will close this for now. Feel free to reopen if you need further assistance.
