### ISSUE TITLE
OCRmyPDF enhancements

### ISSUE THREAD

**Issue by R0Wi** [R0Wi/workflow_ocr#38]
Leftover from https://github.com/R0Wi/workflow_ocr/issues/32

- [ ] Find a way to configure commandline args (via flow parameter?)
    * Language settings

**Comment by LazyGatto** [comment]
Thanks for your plugin =)
But is it possible to set language for tesseract?
For now I just edited directly PdfOcrProcessor.php and adjust line 39
`setCommand("ocrmypdf -l rus --redo-ocr -q - - | cat")`

**Comment by R0Wi** [comment]
Yes this is planned to be configurable with a separate config ui or the workflow ui itself. Currently we don't know when this feature will be implemented but we will track our progress here.

**Comment by R0Wi** [comment]
Moved to https://github.com/R0Wi/workflow_ocr/issues/76
