### ISSUE TITLE
Debian Buster: ocrmypdf outdated

### ISSUE THREAD

**Issue by joergmschulz** [R0Wi/workflow_ocr#46]
Possibly, this wonderful tool can't be used in Debian Buster. It uses ocrmypdf 8.0.1 which issues warnings like 

`WARNING -    2: [tesseract] lots of diacritics - possibly poor OCR
`
This warning leaves the pdf alone / does not add the text layer.

The version 9.8.1 of Alpine works perfectly with the same input file.
Nextcloud log: 
```
OCR for file /joerg.schulz/files/FDS Bau - Sanierung Haus Sonnenblick/Bauherr/Dokumentationen/Projektantrag-SoftwareAG2014.pdf not possible. Message: OCRmyPDF exited abnormally with exit-code 0. Message: WARNING - 4: [tesseract] lots of diacritics - possibly poor OCR WARNING - 2: [tesseract] lots of diacritics - possibly poor OCR
```

**Comment by R0Wi** [comment]
Hi @joergmschulz, a shame that you're experiencing issues with `OCRmyPDF`. As a first information we'd like to mention that we are not willing to replace the tool under the hood. We tried some other tools and packages to achieve the same result earlier which leads to even more problems. So generally speaking we found that `OCRmyPDF` is the best tool to achieve exactly what we want to do with this app in combination with PDF files.

In your case i see the following options:

1. Try to install a newer version of `OCRmyPDF` outside the regular package source. You could give a try on the python installation mentioned [here](https://ocrmypdf.readthedocs.io/en/latest/installation.html#ubuntu-18-04-lts) for Ubuntu 18.04.
2. In our app we could just ignore warnings in general. Even that quite dangerous in my opinion you could try if you're able to process the mentioned file "by hand" when invoking `ocrmypdf inpup.pdf output.pdf` on the commandline. If it just outputs some warnings but the output is generated properly we could think of a more fault tolerant handling inside the app. Please give us some feedback on this or attach the mentioned PDF file if this is possible.

@bahnwaerter anything to add on this?

**Btw**.: i'm also using Debian Buster with `OCRmyPDF` 8.0.1 installed and i did not see similar errors. So it also might be related to the PDF files you want to be processed.

**Comment by joergmschulz** [comment]
attaching one file here // doesn't work, but: https://cloud.faudin.de/s/e2AbYxXR9njcZRC , password dddjjj

**Comment by joergmschulz** [comment]
confirming: when I install the OCRmyPDF version as documented by @R0Wi  above, all works perfectly.

**Comment by R0Wi** [comment]
Glad to hear that everything works as expected now. I'll leave this open until we added the info to the README :-)

**Comment by joergmschulz** [comment]
see https://github.com/R0Wi/workflow_ocr/pull/47

**Comment by R0Wi** [comment]
Thanks for the PR @joergmschulz !
