### ISSUE TITLE
invalid configuration: regular expression is wrong

### ISSUE THREAD

**Issue by nineff** [R0Wi/workflow_ocr#52]
Hi.
I just installed this app and on configuring the flow (like in the example) I'm getting the error:
![error](https://user-images.githubusercontent.com/3100873/109037355-ead17900-76ca-11eb-97af-372832bc38f2.jpg)
It is in german, but the rough translation is: invalid configuration, provided regex is wrong.
I did install `ocrmypdf` and `tesseract-ocr-deu` before installing this app.

I'm on Ubuntu 20.04.2 LTS, php 7.4.3, Nextcloud 21.0.0.18

**Comment by R0Wi** [comment]
Hi i think this is a duplicate of https://github.com/R0Wi/workflow_ocr/issues/41 ?

**Comment by nineff** [comment]
yes, changing from "matches" to "is" helped, thanks!

**Comment by R0Wi** [comment]
Duplicate of https://github.com/nextcloud/server/issues/23666
