### ISSUE TITLE
Question to workflow_ocr

### ISSUE THREAD

**Issue by Peachy74** [R0Wi/workflow_ocr#57]
I can't get the flow OCR to work.
If I upload a new pdf, the cron would have to examine it. I would then have to use the magnifying glass to find a word that is in the pdf, or not?
OCRmyPDF is installed. 
A new FLOW is active. 

<img width="1224" alt="2021-05-21-ocr" src="https://user-images.githubusercontent.com/35838325/119118400-70469a00-ba2a-11eb-8e5b-6e18e28c3f47.png">
 
Do you have a hint for me? 
Thank you and have a nice day

**Comment by R0Wi** [comment]
Thanks for your question. Just to clarify first: the ocr app just applies ocr processing to a given file. This does not mean it does some kind of indexing so for this usecase you'll need additional apps doing some full text search indexing like https://github.com/nextcloud/fulltextsearch.
What you could check to see if the ocr app is working correctly is to check for an additional file version after cron has run. Also you should be able to copy text inside the pdf viewer if you open the document.
To get additional logging information set your loglevel to information and check your server logs after cron has run.

Let me know if you need further information.

**Comment by R0Wi** [comment]
@Peachy74 any news on this? Otherwise i'd close this since it seems not to be related to the OCR app.
