### ISSUE TITLE
Error: "no events are chosen"

### ISSUE THREAD

**Issue by rotdrop** [R0Wi/workflow_ocr#68]
Hi,

after installing the app and the required package ocrmypdf (and tesseract-ocr-deu) I can try to configure the app in the settings menu. I add a mime type filter and then I click on save. However, the response from the system is just "no events are chosen". The nextcloud log does not show any related errors.

The NC version is 22.1.1. 

I have attached a screen-shot:

![Screenshot_20210929_095816](https://user-images.githubusercontent.com/1494769/135227689-d92f640f-28f3-4420-9676-abf79a00241c.png)

**Comment by R0Wi** [comment]
Hi @rotdrop, this is a base functionallity of the NC workflow engine and not directly related to this app. To get the app working 
 and processing pdf documents, please configure the workflow according to the docs (`README`) https://github.com/R0Wi/workflow_ocr/blob/master/doc/img/usual_config_1.jpg so please fill in `When`->`File created, File updated` and `File MIME type`->`is`->`PDF documents`.

I updated your screenshot accordingly:
![image](https://user-images.githubusercontent.com/19730957/135232937-accf14a2-188b-4f4f-96b7-d9a683f7dbd3.png)

You can read more about workflows here: https://nextcloud.com/de/workflow/.

Closing this now, please feel free to reopen if you have any further questions.
