### ISSUE TITLE
trigger on setting a tag

### ISSUE THREAD

**Issue by jkumeboshi** [R0Wi/workflow_ocr#72]
I think that trigger from a specific set of tags would be useful, to avoid to OCR any loaded PDF.

I would like to set a flow triggered by "ocr" tag, so I could:
1) control which files are sent to OCR
2) OCR also any already loaded files

**Comment by R0Wi** [comment]
Hi @jkumeboshi  and thanks for this nice suggestion. I did a quick test and indeed the workflow engine is now possible to trigger workflows based on the `Tag assigned` event (when we first developed this app, that event wasn't yet available).

So yes we're looking forward to implement this feature. Just to pin the use-case:

1. Create a new OCR workflow based on the event type `Tag assigned` with an arbitrary tag name
![image](https://user-images.githubusercontent.com/19730957/142728612-d2b88692-a7af-4b6d-bbf4-a361272d1033.png)

2. Tag the files you want to be processed with the matching tag used in step one by using the file details menu
![image](https://user-images.githubusercontent.com/19730957/142728636-e1f1cf9d-1eac-4e27-aca4-e4b9331074d4.png)

Expected result: the file will be added to the OCR queue and will be processed the next time NC cron runs.

Is that how you would like it to work?

----

**@bahnwaerter FYI some technical todos:**

- [ ] Allow the event name `OCP\SystemTag\ISystemTagObjectMapper::assignTags` with event type `OCP\SystemTag\MapperEvent` in https://github.com/R0Wi/workflow_ocr/blob/2bac1874cec319a4e9e884576f4fb2b513ae7fa3/lib/Operation.php#L126
- [ ] Check if its possible to retrieve the file details from this event in https://github.com/R0Wi/workflow_ocr/blob/2bac1874cec319a4e9e884576f4fb2b513ae7fa3/lib/Operation.php#L100
- [ ] Add some tests for this kind of event
- [ ] Add the use case to the docs

**Comment by jkumeboshi** [comment]
yes, the use case is exactly what I expect (indeed I already tried that exact use case, hoping it was already working :) )

**Comment by R0Wi** [comment]
Shouldn't be too hard to implement this. I'd really appreciate if you volunteer to test this if it's ready 👍

**Comment by jkumeboshi** [comment]
@R0Wi of course I can test it

**Comment by R0Wi** [comment]
@jkumeboshi @bahnwaerter a draft ist ready at https://github.com/R0Wi/workflow_ocr/suites/4422620243/artifacts/116982028. Would be nice if you could give me some feedback :+1:

**Comment by jkumeboshi** [comment]
I did many test this morning and works perfectly for me.
I'll use that test version by now, waiting an update in the app store.

**Comment by R0Wi** [comment]
Thanks for your feedback @jkumeboshi. You can track the progress at https://github.com/R0Wi/workflow_ocr/pull/74. We're working on that feature so we try to push it to the appstore these days.

**Comment by R0Wi** [comment]
FYI this is now officially included in `v1.23.0` (Nextcloud 23) and `v1.22.3` (Nextcloud 22), see https://apps.nextcloud.com/apps/workflow_ocr. Thank you all for contribution :heart:
