### ISSUE TITLE
adding languages list configuration

### ISSUE THREAD

**Issue by jkumeboshi** [R0Wi/workflow_ocr#76]
looking at the execution of ocrmypdf I could see is called as:

`ocrmypdf --redo-ocr -q - - `

that calls tesseract with the "eng" language:

`tesseract -l eng -c textonly_pdf=1 /tmp/com.github.ocrmypdf.cuwitjup/000002_ocr.png /tmp/com.github.ocrmypdf.cuwitjup/000002_ocr_tess pdf txt`

It would be useful to specify in some way a list of languages to pass to tesseract.

The best option would be a global/user settings page that let you specify the languages.
Anyway, since I use Docker and many setting are passed trough ENV variables, a much simpler alternative would be to specify lang list in and ENV variable, such as:

`WORKFLOW_OCR_LANGS=eng+ita+deu`

that should become:

`ocrmypdf -l eng+ita+deu --redo-ocr -q - -`

**Comment by R0Wi** [comment]
See also #38

**Comment by R0Wi** [comment]
Currently working on that, stay tuned 😎

**Comment by jkumeboshi** [comment]
Since I'm running on an octacore arm with 2GB of RAM I'm getng low on RAM when all cores are being used.
Now I'm manually editing a PHP file to add args "-j 2" to allow just 2 tesseract sub process.
I think that something to control parallelism would be useful, since ocrmypdf defaults to all available cores, also igrnoring that a big.Little architettures as have slower cores really much much slower than the "Big" One.
If you would avoid any config GUI,. I think that since this is a tweek One world do just once, a manuale setting in config.php should be enough

**Comment by R0Wi** [comment]
Yeah i'm working on a "per workflow" configuration as well as a "global admin" configuration. So currently i plan to add the [language-settings](https://ocrmypdf.readthedocs.io/en/latest/languages.html) and the [`--remove-background`](https://ocrmypdf.readthedocs.io/en/latest/cookbook.html#image-processing) settings per workflow. Additionally there will be a global admin page where you can set the mentioned [CPU limit](https://ocrmypdf.readthedocs.io/en/latest/pdfsecurity.html?highlight=%22-j%22#limiting-cpu-usage) for all configured workflows. 

Does that make sense? @jkumeboshi could you imagine to test this new features if they're available?

**Comment by jkumeboshi** [comment]
@R0Wi yes, I can tests all new features.
Actually adding specific settings to a workflow item will allow very fine grained control over OCR process, since one can create multiple tags that trigger different settings such as "ocr-deu-no-bg", "ocr-ita", and so on.

**Comment by R0Wi** [comment]
@jkumeboshi @bahnwaerter a first draft for NC 22 is available now https://github.com/R0Wi/workflow_ocr/suites/4570045796/artifacts/122931156.

What's working: setting language(s) and `remove-background`-flag per workflow.

What's still missing:

- [ ] Localization
- [ ] Fix (unit-)tests
- [ ] Global admin page not yet functional
- [ ] Additional integration tests for VUE components

Would be happy to get some feedback :sunglasses:

**Comment by jkumeboshi** [comment]
well, actually the command line args are added correctly: I've tested "ita+eng" and just "ita", it works fine and I can see the "-l eng+ita" and "-l ita" in the command line.
The "--remove-background" option is correctly added too, although in that case ocrmypdf fails to scan the pdf files.

**Comment by R0Wi** [comment]
Could you elaborate on why the command fails? Are there any logs?

**Comment by jkumeboshi** [comment]
The problem was that I was just trying to re-process already OCRed files, running manually the cmd line returns following error:

```
PriorOcrFoundError: page already has text! - aborting (use --force-ocr to force OCR;  see also help for the arguments --skip-text and --redo-ocr
```

and manually forcing `--redo-ocr ` shows me the reason:
```
--redo-ocr is not currently compatible with --deskew, --clean-final, and --remove-background
```

so it's a limit of ocrmypdf, running it on a file never OCRed before with `--remove-background` just works.

**Comment by R0Wi** [comment]
I also noticed this behaviour so this is why currently either `--remove-background` OR `--redo-ocr` is set by the app 😄

**Comment by R0Wi** [comment]
This feature is included in [`v1.22.5`](https://github.com/R0Wi/workflow_ocr/releases/tag/v1.22.5) and [`v1.23.2`](https://github.com/R0Wi/workflow_ocr/releases/tag/v1.23.2) 🚀

**Comment by jkumeboshi** [comment]
the CPU settings is not working for me (I'm using updated FF).
When I try to set the CPU number, nothing happens.

in the dev console I can see following:

```
Errore mapping di origine: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
URL risorsa: https://cloud.fedibox.com/custom_apps/workflow_ocr/js/workflow_ocr-main.js?v=97330a9c-18
URL mapping di origine: workflow_ocr-main.js.map?v=628f834467811c9c16be
```

**Comment by R0Wi** [comment]
Cannot reproduce this issue. Could you clear your browsers cache? And could you please share the network tab of your browser while changing the CPU setting?

**Comment by jkumeboshi** [comment]
I did gave up for a while, until today I found that the component were not being updated using the NC auto update feature, also deactivating and removing the plugin since it were not removed from the FS.
I've manually removed and re installed from App market it and now works fine.

**Comment by R0Wi** [comment]
Great that it works for you now! Sorry that you had troubles but that doesn't sound like an issue related to this app but rather to NC itself. Let us know if you have further questions :-)
